<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SeedLibraryData extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();

        // 1. Enrich / Seed Books
        $books = [
            [
                'id' => 1,
                'title' => 'Petualangan Si Kancil di Hutan Ajaib',
                'author' => 'A. Kurniawan',
                'illustrator' => 'Dewi Lestari',
                'publisher' => 'Parentela Kids Press',
                'year' => 2024,
                'language' => 'Bahasa Indonesia',
                'age_min' => 3,
                'age_max' => 7,
                'reading_level' => 'Beginner',
                'category' => 'Cerita Anak',
                'genre' => 'Dongeng & Fabel',
                'synopsis' => 'Kisah seru dan mendidik tentang kecerdikan Si Kancil menolong sahabat-sahabat hutannya dari kekeringan dengan kerja sama dan gotong royong.',
                'pages' => 36,
                'cover' => 'kancil-ajaib.jpg',
                'format' => 'E-book',
                'is_illustrated' => 1,
                'rating' => 4.95,
                'total_ratings' => 142,
                'is_best_seller' => 1,
                'is_new_arrival' => 1,
            ],
            [
                'id' => 2,
                'title' => 'Mengenal Warna & Bentuk Ceria',
                'author' => 'B. Santoso',
                'illustrator' => 'Rina Sasmita',
                'publisher' => 'Pustaka Balita Cerdas',
                'year' => 2024,
                'language' => 'Bahasa Indonesia',
                'age_min' => 1,
                'age_max' => 3,
                'reading_level' => 'Beginner',
                'category' => 'Edukasi',
                'genre' => 'Buku Bergambar',
                'synopsis' => 'Buku interaktif visual warna-warni yang mengajak balita mengenali bentuk geometri dan warna pelangi melalui objek sehari-hari di sekitar rumah.',
                'pages' => 24,
                'cover' => 'warna-ceria.jpg',
                'format' => 'E-book',
                'is_illustrated' => 1,
                'rating' => 4.88,
                'total_ratings' => 95,
                'is_best_seller' => 0,
                'is_new_arrival' => 1,
            ],
            [
                'id' => 3,
                'title' => 'Psikologi Perkembangan Anak Usia Dini',
                'author' => 'Dr. C. Dewi, M.Psi',
                'illustrator' => 'Tim Infografis Parentela',
                'publisher' => 'Parentela Publishing',
                'year' => 2023,
                'language' => 'Bahasa Indonesia',
                'age_min' => 18,
                'age_max' => 99,
                'reading_level' => 'Advanced',
                'category' => 'Parenting',
                'genre' => 'Psikologi & Pola Asuh',
                'synopsis' => 'Panduan wajib orang tua milenial dan gen-Z untuk memahami ledakan emosi tantrum, lompatan milestone kognitif, dan teknik komunikasi afektif yang memvalidasi perasaan anak.',
                'pages' => 218,
                'cover' => 'psikologi-anak.jpg',
                'format' => 'E-book',
                'is_illustrated' => 0,
                'rating' => 4.98,
                'total_ratings' => 310,
                'is_best_seller' => 1,
                'is_new_arrival' => 0,
            ],
            [
                'id' => 4,
                'title' => 'Malam Bintang Kejora untuk Kiki',
                'author' => 'Nadia Amalia',
                'illustrator' => 'Fajar Nugraha',
                'publisher' => 'Parentela Kids Press',
                'year' => 2024,
                'language' => 'Bahasa Indonesia',
                'age_min' => 2,
                'age_max' => 6,
                'reading_level' => 'Beginner',
                'category' => 'Dongeng',
                'genre' => 'Dongeng Pengantar Tidur',
                'synopsis' => 'Cerita berima dengan ilustrasi lembut langit malam yang membantu anak menurunkan stimulasi sebelum tidur, menumbuhkan rasa aman dan tidur nyenyak.',
                'pages' => 28,
                'cover' => 'bintang-kiki.jpg',
                'format' => 'Audiobook',
                'is_illustrated' => 1,
                'rating' => 4.92,
                'total_ratings' => 88,
                'is_best_seller' => 1,
                'is_new_arrival' => 1,
            ],
            [
                'id' => 5,
                'title' => 'Bumi Kita yang Penuh Keajaiban',
                'author' => 'Prof. Hendra Wijaya',
                'illustrator' => 'Alita Studio',
                'publisher' => 'Sains Cilik Nusantara',
                'year' => 2024,
                'language' => 'Bahasa Indonesia',
                'age_min' => 6,
                'age_max' => 10,
                'reading_level' => 'Intermediate',
                'category' => 'Edukasi',
                'genre' => 'Sains Populer Anak',
                'synopsis' => 'Mengapa laut berombak? Dari mana asalnya hujan? Jelajahi fenomena sains alam dengan gaya bahasa renyah dan analogi yang mudah dicerna anak usia SD.',
                'pages' => 52,
                'cover' => 'bumi-keajaiban.jpg',
                'format' => 'E-book',
                'is_illustrated' => 1,
                'rating' => 4.85,
                'total_ratings' => 64,
                'is_best_seller' => 0,
                'is_new_arrival' => 1,
            ],
            [
                'id' => 6,
                'title' => 'Si Beruang yang Belajar Berbagi',
                'author' => 'Ratna Puspita',
                'illustrator' => 'Maya Kartika',
                'publisher' => 'Sahabat Cerita Kecil',
                'year' => 2023,
                'language' => 'Bahasa Indonesia',
                'age_min' => 3,
                'age_max' => 6,
                'reading_level' => 'Beginner',
                'category' => 'Cerita Anak',
                'genre' => 'Pendidikan Karakter',
                'synopsis' => 'Boni si beruang memiliki sekeranjang buah stroberi manis. Lewat kisah menyentuh ini, Boni belajar betapa bahagianya berbagi kenikmatan dengan sahabat-sahabatnya.',
                'pages' => 32,
                'cover' => 'beruang-berbagi.jpg',
                'format' => 'E-book',
                'is_illustrated' => 1,
                'rating' => 4.90,
                'total_ratings' => 112,
                'is_best_seller' => 1,
                'is_new_arrival' => 0,
            ],
            [
                'id' => 7,
                'title' => 'Seni Berkomunikasi Tanpa Membentak',
                'author' => 'Ayah Edy Sujarwo',
                'illustrator' => '',
                'publisher' => 'Parentela Parenting Press',
                'year' => 2024,
                'language' => 'Bahasa Indonesia',
                'age_min' => 18,
                'age_max' => 99,
                'reading_level' => 'Advanced',
                'category' => 'Parenting',
                'genre' => 'Gentle Parenting',
                'synopsis' => 'Solusi nyata menjaga ketenangan hati orang tua di saat situasi tegang, mengubah kalimat bentakan menjadi instruksi penuh kasih yang didengar anak dengan senang hati.',
                'pages' => 184,
                'cover' => 'komunikasi-anak.jpg',
                'format' => 'E-book',
                'is_illustrated' => 0,
                'rating' => 4.96,
                'total_ratings' => 240,
                'is_best_seller' => 1,
                'is_new_arrival' => 1,
            ],
            [
                'id' => 8,
                'title' => 'Petualangan Detektif Cilik Reno',
                'author' => 'Bagus Prayogo',
                'illustrator' => 'Kresna Art',
                'publisher' => 'Mata Air Kids',
                'year' => 2024,
                'language' => 'Bahasa Indonesia',
                'age_min' => 7,
                'age_max' => 12,
                'reading_level' => 'Intermediate',
                'category' => 'Aktivitas Anak',
                'genre' => 'Misteri & Teka-Teki',
                'synopsis' => 'Buku cerita bergambar teka-teki logika di mana pembaca ikut memecahkan jejak misteri kucing tetangga yang hilang bersama Detektif Reno!',
                'pages' => 48,
                'cover' => 'detektif-reno.jpg',
                'format' => 'E-book',
                'is_illustrated' => 1,
                'rating' => 4.79,
                'total_ratings' => 53,
                'is_best_seller' => 0,
                'is_new_arrival' => 1,
            ],
            [
                'id' => 9,
                'title' => 'Mengenal Emosiku: Saat Aku Marah & Sedih',
                'author' => 'Citra Anindya, S.Psi',
                'illustrator' => 'Dina Syafira',
                'publisher' => 'Pustaka Bintang Kecil',
                'year' => 2024,
                'language' => 'Bahasa Indonesia',
                'age_min' => 3,
                'age_max' => 8,
                'reading_level' => 'Beginner',
                'category' => 'Tumbuh Kembang',
                'genre' => 'Kecerdasan Emosional',
                'synopsis' => 'Membantu si kecil mengenali sinyal tubuh saat rasa marah atau sedih datang, lengkap dengan teknik pernapasan sederhana "meniup balon imajinasi" untuk menenangkan diri.',
                'pages' => 30,
                'cover' => 'emosi-anak.jpg',
                'format' => 'E-book',
                'is_illustrated' => 1,
                'rating' => 4.94,
                'total_ratings' => 178,
                'is_best_seller' => 1,
                'is_new_arrival' => 1,
            ],
            [
                'id' => 10,
                'title' => 'Panduan MPASI Praktis & Gizi Seimbang',
                'author' => 'dr. Nurul Hidayah, Sp.A',
                'illustrator' => 'Tim Dapur Cilik Parentela',
                'publisher' => 'Parentela Publishing',
                'year' => 2024,
                'language' => 'Bahasa Indonesia',
                'age_min' => 18,
                'age_max' => 99,
                'reading_level' => 'Intermediate',
                'category' => 'Parenting',
                'genre' => 'Gizi & Nutrisi',
                'synopsis' => 'Buku panduan tekstur dan menu makanan pendamping ASI dari usia 6 hingga 24 bulan, tips mencegah GTM (Gerakan Tutup Mulut), dan kecukupan zat besi serta protein hewani.',
                'pages' => 160,
                'cover' => 'mpasi-panduan.jpg',
                'format' => 'E-book',
                'is_illustrated' => 1,
                'rating' => 4.97,
                'total_ratings' => 280,
                'is_best_seller' => 1,
                'is_new_arrival' => 1,
            ],
            [
                'id' => 11,
                'title' => 'Halo Sahabat Binatang Laut!',
                'author' => 'Taufik Hidayat',
                'illustrator' => 'Gita Ocean Art',
                'publisher' => 'Samudra Pustaka Balita',
                'year' => 2024,
                'language' => 'Bahasa Indonesia',
                'age_min' => 2,
                'age_max' => 5,
                'reading_level' => 'Beginner',
                'category' => 'Buku Bergambar',
                'genre' => 'Ensiklopedia Cilik',
                'synopsis' => 'Menyelam ke dalam terumbu karang indah! Temui lumba-lumba lincah, penyu bijak, dan kepiting kecil yang berjalan miring dalam ilustrasi penuh warna.',
                'pages' => 26,
                'cover' => 'sahabat-laut.jpg',
                'format' => 'E-book',
                'is_illustrated' => 1,
                'rating' => 4.87,
                'total_ratings' => 76,
                'is_best_seller' => 0,
                'is_new_arrival' => 1,
            ],
            [
                'id' => 12,
                'title' => 'Dongeng Pohon Apel yang Dermawan',
                'author' => 'Shelby Pratama',
                'illustrator' => 'Hendra Saputra',
                'publisher' => 'Pustaka Klasik Indonesia',
                'year' => 2023,
                'language' => 'Bahasa Indonesia',
                'age_min' => 4,
                'age_max' => 9,
                'reading_level' => 'Beginner',
                'category' => 'Dongeng',
                'genre' => 'Fabel & Nilai Moral',
                'synopsis' => 'Kisah legendaris tentang ketulusan cinta sejati antara sebatang pohon apel rindang dan seorang anak manusia dari masa kecil hingga usia senja.',
                'pages' => 38,
                'cover' => 'pohon-apel.jpg',
                'format' => 'Audiobook',
                'is_illustrated' => 1,
                'rating' => 4.91,
                'total_ratings' => 134,
                'is_best_seller' => 1,
                'is_new_arrival' => 0,
            ],
        ];

        foreach ($books as $b) {
            $existing = $db->table('books')->where('id', $b['id'])->get()->getRowArray();
            if ($existing) {
                $db->table('books')->where('id', $b['id'])->update($b);
            } else {
                $db->table('books')->insert($b);
            }
        }

        // 2. Enrich Storytelling
        $stories = [
            [
                'id' => 1,
                'title' => 'Kisah Kelinci Cepat & Kura-Kura Tekun',
                'category' => 'Dongeng Karakter',
                'description' => 'Dongeng audio klasik dengan efek suara alam yang kaya, mengajarkan anak arti konsistensi, pantang menyerah, dan saling menghormati.',
                'audio_url' => '#',
                'cover' => '',
                'narrator' => 'Kak Nia (Parentela Storyteller)',
                'duration' => '07:45',
                'is_featured' => 1,
            ],
            [
                'id' => 2,
                'title' => 'Misteri Suara di Balik Lemari Kiki',
                'category' => 'Petualangan & Keberanian',
                'description' => 'Membantu anak mengatasi ketakutan akan gelap dan suara malam lewat narasi lucu, hangat, dan penuh kejutan menyenangkan.',
                'audio_url' => '#',
                'cover' => '',
                'narrator' => 'Kak Dimas & Kak Sarah',
                'duration' => '09:15',
                'is_featured' => 1,
            ],
            [
                'id' => 3,
                'title' => 'Bintang Kejora yang Tersesat di Awan',
                'category' => 'Pengantar Tidur Santai',
                'description' => 'Dongeng audio dengan melodi pengantar tidur instrumental santai untuk memperlambat detak jantung dan membawa si kecil terlelap damai.',
                'audio_url' => '#',
                'cover' => '',
                'narrator' => 'Bunda Maya (Konselor Tidur Anak)',
                'duration' => '11:20',
                'is_featured' => 1,
            ],
        ];

        foreach ($stories as $s) {
            $existingStory = $db->table('storytelling')->where('id', $s['id'])->get()->getRowArray();
            if ($existingStory) {
                $db->table('storytelling')->where('id', $s['id'])->update($s);
            } else {
                $db->table('storytelling')->insert($s);
            }
        }

        echo "Seeding completed successfully: " . count($books) . " books and " . count($stories) . " stories updated/inserted.\n";
    }
}
